### ISSUE TITLE
 'Aerofoil 2 Activation time'  & 'Aerofoil 2 De-activation time' writes as SetOffense() in Structure.xml

### ISSUE THREAD

**Issue by 80s-Time-Warp** [DevilboxGames/ReincarnationTools#2]
'Aerofoil 2 Activation time'  & 'Aerofoil 2 De-activation time' writes as SetOffense() in Structure.xml

Steps to Reproduce:
Car Characteristics Modifier -> Air Brake & Spoiler Settings -> Aerofoil 2 -> 'Activation Time' & 'Deactivation Time'

**Comment by DevilboxGames** [comment]
I'm pretty sure this had already been fixed.

**Comment by 80s-Time-Warp** [comment]
Confirmed as resolved in newest version :)
