### ISSUE TITLE
CNT Hierarchy Modifier Node types 'VFXI' & 'EMT2' export as 'Null'

### ISSUE THREAD

**Issue by 80s-Time-Warp** [DevilboxGames/ReincarnationTools#3]
The following types export as Null when a CNT is exported.
- VFXI
- EMT2

Steps to Reproduce:
CNT Hierarchy -> Node Type -> Set to 'VFXI' & 'EMT2'
Export CNT

**Comment by DevilboxGames** [comment]
It seems like EMT2 isn't used by the game and it has a lot of unknown data stored in the CNT which I haven't written tools for, so I've just removed it from the options. VFXI should work now and I've added shrb which is the foliage node.

**Comment by 80s-Time-Warp** [comment]
Resolved in newest version.

- Confirmed EMT2 is no longer present in Node Type drop down
- VFXI nodes now export correctly.
